In [27]:
import pandas as pd 
import numpy as np

from sklearn.linear_model import LinearRegression

In [28]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/1000)
# Read the CSV → select 4 numerical columns → divide all values by 1000 → round the values → store the result in df.
np.random.seed(42)
# you will get the same random selection each time you run the code, assuming the same NumPy/Pandas behaviour. # similar to random_state=42
df = df.sample(5)
df

,R&D Spend,Administration,Marketing Spend,Profit
13,92.0,135.0,253.0,134.0
39,39.0,83.0,175.0,81.0
30,62.0,116.0,91.0,100.0
45,1.0,124.0,2.0,65.0
17,95.0,145.0,283.0,125.0


In [29]:
df = df.iloc[:,0:-1]
df

,R&D Spend,Administration,Marketing Spend
13,92.0,135.0,253.0
39,39.0,83.0,175.0
30,62.0,116.0,91.0
45,1.0,124.0,2.0
17,95.0,145.0,283.0


In [30]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

/var/folders/3s/ns8l4nq14cq62jr4rlgm2hv80000gn/T/ipykernel_13463/766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/var/folders/3s/ns8l4nq14cq62jr4rlgm2hv80000gn/T/ipykernel_13463/766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/var/folders/3s/ns8l4nq14cq62jr4rlgm2hv80000gn/T/ipykernel_13463/766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1]

In [31]:
df.head()

,R&D Spend,Administration,Marketing Spend
13,92.0,135.0,253.0
39,NaN,83.0,175.0
30,62.0,116.0,91.0
45,1.0,NaN,2.0
17,95.0,145.0,NaN


In [32]:
# Step1 -> impute all the missing value with the mean of respective columns 
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [33]:
# 0th iteration 
df0.head()

,R&D Spend,Administration,Marketing Spend
13,92.0,135.00,253.00
39,62.5,83.00,175.00
30,62.0,116.00,91.00
45,1.0,119.75,2.00
17,95.0,145.00,130.25


In [34]:
# remove the col1 imputed value 
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
13,92.0,135.00,253.00
39,NaN,83.00,175.00
30,62.0,116.00,91.00
45,1.0,119.75,2.00
17,95.0,145.00,130.25


In [36]:
# using column 1 and 2 and row 0,2,3,4 for training the model 
X = df1.iloc[[0,2,3,4],1:3]
X

,Administration,Marketing Spend
13,135.00,253.00
30,116.00,91.00
45,119.75,2.00
17,145.00,130.25


In [38]:
y = df1.iloc[[0,2,3,4],0]
y

13    92.0
30    62.0
45     1.0
17    95.0
Name: R&D Spend, dtype: float64

In [39]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:3].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25.78858722])

In [40]:
df1.iloc[1,0] = 25.788
df1

,R&D Spend,Administration,Marketing Spend
13,92.000,135.00,253.00
39,25.788,83.00,175.00
30,62.000,116.00,91.00
45,1.000,119.75,2.00
17,95.000,145.00,130.25


In [42]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
13,92.000,135.0,253.00
39,25.788,83.0,175.00
30,62.000,116.0,91.00
45,1.000,NaN,2.00
17,95.000,145.0,130.25


In [43]:
X = df1.iloc[[0,1,2,4],[0,2]]
X

,R&D Spend,Marketing Spend
13,92.000,253.00
39,25.788,175.00
30,62.000,91.00
17,95.000,130.25


In [44]:
y = df1.iloc[[0,1,2,4],1]
y

13    135.0
39     83.0
30    116.0
17    145.0
Name: Administration, dtype: float64

In [45]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([68.96756848])

In [46]:
df1.iloc[3,1] = 68.96

In [47]:
df1

,R&D Spend,Administration,Marketing Spend
13,92.000,135.00,253.00
39,25.788,83.00,175.00
30,62.000,116.00,91.00
45,1.000,68.96,2.00
17,95.000,145.00,130.25


In [48]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
13,92.000,135.00,253.0
39,25.788,83.00,175.0
30,62.000,116.00,91.0
45,1.000,68.96,2.0
17,95.000,145.00,NaN


In [49]:
X = df1.iloc[0:4,0:2]
X

,R&D Spend,Administration
13,92.000,135.00
39,25.788,83.00
30,62.000,116.00
45,1.000,68.96


In [50]:
y = df1.iloc[0:4,-1]
y

13    253.0
39    175.0
30     91.0
45      2.0
Name: Marketing Spend, dtype: float64

In [51]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46.22867086])

In [52]:
df1.iloc[4,-1] = 46.228

In [53]:
# After 1st Iteration
df1

,R&D Spend,Administration,Marketing Spend
13,92.000,135.00,253.000
39,25.788,83.00,175.000
30,62.000,116.00,91.000
45,1.000,68.96,2.000
17,95.000,145.00,46.228


In [54]:
# Subtract 0th iteration from 1st iteration

df1 - df0

,R&D Spend,Administration,Marketing Spend
13,0.000,0.00,0.000
39,-36.712,0.00,0.000
30,0.000,0.00,0.000
45,0.000,-50.79,0.000
17,0.000,0.00,-84.022


In [56]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

,R&D Spend,Administration,Marketing Spend
13,92.0,135.00,253.000
39,NaN,83.00,175.000
30,62.0,116.00,91.000
45,1.0,68.96,2.000
17,95.0,145.00,46.228


In [57]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25.6443894])

In [58]:
df2.iloc[1,0] = 25.644

In [59]:

df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([68.85296392])

In [60]:

df2.iloc[3,1] = 68.85

In [62]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([41.8535182])

In [63]:
df2.iloc[4,-1] = 41.85

In [ ]:
# After 2nd iteration 
df2

,R&D Spend,Administration,Marketing Spend
13,92.000,135.00,253.00
39,25.644,83.00,175.00
30,62.000,116.00,91.00
45,1.000,68.85,2.00
17,95.000,145.00,41.85


In [65]:
# 2nd iteration - 1st iteration 
df2 - df1

,R&D Spend,Administration,Marketing Spend
13,0.000,0.00,0.000
39,-0.144,0.00,0.000
30,0.000,0.00,0.000
45,0.000,-0.11,0.000
17,0.000,0.00,-4.378


In [66]:
# similarly create more iteration till we get almost zeros in the place of NaN in the pandas dataframe or we can run fixed no. of iteration like 100 or 50 