In [88]:
import pickle 
import numpy as np 

In [89]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [90]:
# Assume user input 
# Pclass/gender/age/Sibsp/Parch/Fare/Embarked
test_input = np.array([1,'Female',20.0,1,2,100.5,'S'],dtype=object).reshape(1,7) 
# dtype=object tells NumPy: "Keep each element in its original type, even though the array contains mixed data types. otherwise if we do not set any data type then the numpy will set automatically some data type it can be string then for all column the data type will be string which is not good.
# reshape(1,7) tells scikit-learn: "This is one sample with seven features."
# [2, 'male', 31.0, 0, 0, 10.5, 'S'] -> This is a 1-dimensional array with shape: (7,)
# But when making predictions, scikit-learn expects the input to be 2-dimensional:
# (number_of_samples, number_of_features)
# (1, 7)
# Before reshape -> [2, 'male', 31.0, 0, 0, 10.5, 'S']
# After reshape -> [[2, 'male', 31.0, 0, 0, 10.5, 'S']]

In [91]:
test_input

array([[1, 'Female', 20.0, 1, 2, 100.5, 'S']], dtype=object)

In [92]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
# or
# test_input_sex = ohe_sex.transform(test_input[:,1:2])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [93]:
test_input_sex

array([[0., 0.]])

In [94]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [95]:
test_input_embarked

array([[0., 0., 1.]])

In [96]:
test_input_age = test_input[:,2].reshape(1,1)

In [97]:
test_input_age

array([[20.0]], dtype=object)

In [98]:
test_input_tranformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [99]:
test_input_tranformed.shape

(1, 10)

In [100]:
clf.predict(test_input_tranformed)

array([1])